# -*- coding: utf-8 -*-

PALETTE = [
    ('bg', '', '', '', 'black', 'g93'),
    ('header', '', '', '', '#fff', '#d00'),
    ('h1', '', '', '', '#fff,bold', '#d00'),
    ('h2', '', '', '', '#faa', '#d00'),
    ('card', '', '', '', '#333', '#fff'),
    ('text', '', '', '', '#333', '#fff'),
    ('pic', '', '', '', '#fff', 'dark gray'),
    ('hr', '', '', '', 'g93', '#fff'),
    ('button', '', '', '', '#d00', '#fff'),
    ('copy', '', '', '', 'g70', 'g93'),
    ('text bold', '', '', '', '#333,bold', '#fff'),
    ('text italic', 'dark gray', 'white', '', '#777', '#fff'),
    ('image button', '', '', '', 'g70', '#fff'),
    ('image button focus', '', '', '', '#f00', '#fff'),
    ('input', '', '', '', 'g70', '#fff'),
    ('input focus', '', '', '', 'g42', '#fff'),
    ('error', '', '', '', '#d00', '#fff'),
    ('text focus', '', '', '', '#333', 'light gray'),
    ('bold focus', '', '', '', '#333,bold', 'light gray'),
    ('progress', '', '', '', '#d00', '#fff'),
    ('remaining', '', '', '', 'g93', '#fff'),
    ('yellow_title', '', '', '', 'black,bold', '#fc0'),
    ('failed', '', '', '', '#d00,bold', '#fff'),
    ('passed', '', '', '', '#0a0,bold', '#fff'),
    ('warning', '', '', '', '#f80,bold', '#fff'),
    ('info', '', '', '', 'g70,bold', '#fff'),
    ('header red', '', '', '', '#d00,bold', '#fff'),
]
