# -*- coding: utf-8 -*-

palette = [
    ('bg', '', '', '', 'black', 'g93'),
    ('header', '', '', '', '#fff', '#d00'),
    ('h1', '', '', '', '#fff,bold', '#d00'),
    ('h2', '', '', '', '#faa', '#d00'),
    ('card', '', '', '', '#333', '#fff'),
    ('text', '', '', '', '#333', '#fff'),
    ('pic', '', '', '', '#fff', 'dark gray'),
    ('hr', '', '', '', 'g93', '#fff'),
    ('button', '', '', '', '#d00', '#fff'),
    ('copy', '', '', '', 'g70', 'g93'),
    ('text bold', '', '', '', '#333,bold', '#fff'),
    ('text italic', '', '', '', '#333,italics', '#fff'),
    ('image button', '', '', '', 'g70', '#fff'),
    ('image button focus', '', '', '', '#f00', '#fff'),
    ('input', '', '', '', 'g70', '#fff'),
    ('input focus', '', '', '', 'g42', '#fff'),
    ('error', '', '', '', '#f00', '#fff'),
    ('text focus', '', '', '', '#333', 'light gray'),
    ('bold focus', '', '', '', '#333,bold', 'light gray'),
    ('progress', '', '', '', 'light red', '#fff'),
    ('remaining', '', '', '', 'light gray', '#fff'),
    ('yellow_title', '', '', '', 'black,bold', '#fc0'),
    ('ok', '', '', '', 'light green', '#fff'),
    ('warning', '', '', '', '#f40', '#fff'),
    ('info', '', '', '', 'light cyan', '#fff'),
    ('header red', '', '', '', 'light red,bold', '#fff'),
    ('body','', '', '', '#333', 'g93'),
    ('browser focus', '', '', 'standout', '#333', 'light gray'),
    ('dirmark', '', '','','light red,bold','g93'),
    
    
]
